onaio/js-tools

packages/gatekeeper/README.md, packages/gatekeeper/dist/components/logout.js, packages/gatekeeper/dist/helpers/constants.js, packages/gatekeeper/dist/index.js, packages/gatekeeper/dist/types/components/logout.d.ts, packages/gatekeeper/dist/types/helpers/constants.d.ts, packages/gatekeeper/dist/types/index.d.ts, packages/gatekeeper/package.json, packages/gatekeeper/src/components/logout.tsx, packages/gatekeeper/src/components/tests/__snapshots__/logout.test.tsx.snap, packages/gatekeeper/src/components/tests/login.test.tsx, packages/gatekeeper/src/components/tests/logout.test.tsx, packages/gatekeeper/src/helpers/constants.ts, packages/gatekeeper/src/index.ts
Add a logout component to the gatekeeper package.
=> Gatekeeper: Add logout component

packages/session-reducer/dist/types/index.d.ts, packages/session-reducer/src/index.ts
Add better type definitions for selectors
=> Fix session reducer

packages/connected-private-route/dist/types/index.d.ts, packages/connected-private-route/src/index.tsx, packages/connected-private-route/src/tests/__snapshots__/index.test.tsx.snap, packages/connected-private-route/src/tests/index.test.tsx, packages/gatekeeper/README.md, packages/gatekeeper/dist/types/ducks/gatekeeper.d.ts, packages/gatekeeper/src/ducks/gatekeeper.ts
=> Fix connected private route

packages/SupersetConnector/README.md, packages/SupersetConnector/dist/auth.js, packages/SupersetConnector/package.json, packages/SupersetConnector/src/api.js, packages/SupersetConnector/src/auth.js, packages/SupersetConnector/src/tests/supersetConnector.test.js
=> Add dynamic oAuth2 provider for SupersetConnector

packages/SupersetConnector/dist/index.js, packages/SupersetConnector/dist/types/index.d.ts, packages/SupersetConnector/src/index.ts
=> Superst connector export utils

packages/SupersetConnector/README.md
=> Update SupersetConnector README.md

packages/DrillDownTable/README.md, packages/DrillDownTable/dist/index.js, packages/DrillDownTable/dist/types/index.d.ts, packages/DrillDownTable/src/index.tsx, packages/SupersetConnector/dist/types/utils.d.ts, packages/SupersetConnector/src/utils.ts, stories/DrillDownTable/DrillDownTable.stories.tsx, stories/DrillDownTable/fixtures.ts
- Fix bug that prevented drill down from working when the root parent id was not `null`
- Fix: #80
- Add story for large dataset for DrillDownTable
=> Fix DrillDownTable bug

packages/session-reducer/README.md, packages/session-reducer/src/index.ts, packages/session-reducer/src/tests/fixtures.ts, packages/session-reducer/src/tests/index.test.ts
Fix issue: #82. Add selectors defined here https://github.com/onaio/reveal-frontend/blob/master/src/store/selectors.ts to the session-reducer package.
=> Add selectors to the session-reducer package

packages/session-reducer/dist/index.js, packages/session-reducer/dist/types/index.d.ts
=> Transpile and generate type definations for session reducer package 

packages/HeaderBreadcrumb/README.md, packages/HeaderBreadcrumb/dist/index.js, packages/HeaderBreadcrumb/dist/types/index.d.ts, packages/HeaderBreadcrumb/package.json, packages/HeaderBreadcrumb/src/headerbreadcrumb.css, packages/HeaderBreadcrumb/src/index.tsx, packages/HeaderBreadcrumb/src/tests/__snapshots__/index.test.tsx.snap, packages/HeaderBreadcrumb/src/tests/index.test.tsx, packages/HeaderBreadcrumb/tsconfig.json, stories/HeaderBreadCrumb/HeaderBreadCrumb.stories.tsx, yarn.lock
=> Migrate HeadBreadcrumb component

packages/ListView/README.md
Use `@onaio/list-view` instead of `@onaio/listview`
=> Fix list-view typo

packages/superset-reducer/README.md, packages/superset-reducer/dist/index.js, packages/superset-reducer/dist/types/index.d.ts, packages/superset-reducer/package.json, packages/superset-reducer/src/index.ts, packages/superset-reducer/src/tests/index.test.ts, packages/superset-reducer/tsconfig.json
=>  Package Superset reducer module into a js-tool package

README.md
- Add links for resources that could be useful to newbies in the Readme
Signed-off-by: Racheal Mwatela <mwatelaraycee33@gmail.com>
=> Add resources in readme

packages/gatekeeper/README.md, packages/gatekeeper/dist/components/callback.js, packages/gatekeeper/dist/components/login.js, packages/gatekeeper/dist/components/logout.js, packages/gatekeeper/dist/ducks/gatekeeper.js, packages/gatekeeper/dist/helpers/constants.js, packages/gatekeeper/dist/helpers/oauth.js, packages/gatekeeper/dist/helpers/services.js, packages/gatekeeper/dist/helpers/utils.js, packages/gatekeeper/dist/index.js, packages/gatekeeper/dist/types/components/logout.d.ts, packages/gatekeeper/dist/types/helpers/constants.d.ts, packages/gatekeeper/dist/types/helpers/utils.d.ts, packages/gatekeeper/src/components/logout.tsx, packages/gatekeeper/src/components/tests/logout.test.tsx, packages/gatekeeper/src/components/tests/utils.test.ts, packages/gatekeeper/src/helpers/constants.ts, packages/gatekeeper/src/helpers/utils.ts
=> Add logout from auth server functionality

packages/ProgressIndicators/README.md, packages/ProgressIndicators/package.json
- Update progress bar readme
- Remove spacing in types value on package.json
Signed-off-by: Racheal Mwatela <mwatelaraycee33@gmail.com>
=> Update ProgressBar Readme with Correct Package Name

packages/ProgressIndicators/dist/ProgressBar/index.js, packages/ProgressIndicators/dist/index.js, packages/ProgressIndicators/dist/types/ProgressBar/index.d.ts, packages/ProgressIndicators/dist/types/index.d.ts, packages/ProgressIndicators/src/ProgressBar/index.tsx, packages/ProgressIndicators/src/ProgressBar/tests/__snapshots__/index.test.tsx.snap, packages/ProgressIndicators/src/ProgressBar/tests/index.test.tsx, packages/ProgressIndicators/src/index.tsx
Use class components in progress bar instead of functional ines
Signed-off-by: Racheal Mwatela <mwatelaraycee33@gmail.com>
=> Use class components for ProgressBar

package.json, packages/utils/README.md, packages/utils/dist/index.js, packages/utils/dist/types.js, packages/utils/dist/types/index.d.ts, packages/utils/dist/types/types.d.ts, packages/utils/dist/types/utils.d.ts, packages/utils/dist/utils.js, packages/utils/package.json, packages/utils/src/index.ts, packages/utils/src/tests/types.test.ts, packages/utils/src/tests/utils.test.ts, packages/utils/src/types.ts, packages/utils/src/utils.ts, packages/utils/tsconfig.json, yarn.lock
=> Add @onaio/utils package

packages/cbv/README.md, packages/cbv/dist/Base.js, packages/cbv/dist/ObjectList.js, packages/cbv/dist/SingleObject.js, packages/cbv/dist/index.js, packages/cbv/dist/types/Base.d.ts, packages/cbv/dist/types/ObjectList.d.ts, packages/cbv/dist/types/SingleObject.d.ts, packages/cbv/dist/types/index.d.ts, packages/cbv/package.json, packages/cbv/src/Base.tsx, packages/cbv/src/ObjectList.tsx, packages/cbv/src/SingleObject.tsx, packages/cbv/src/index.ts, packages/cbv/src/tests/ObjectList.test.tsx, packages/cbv/src/tests/SingleObject.test.tsx, packages/cbv/src/tests/ducks/messages.ts, packages/cbv/tsconfig.json, yarn.lock
Fix: #126
- Adds the Class Based views
- Adds tests for the Class Based views
- Adds a README for the Class Based views
- No need for a story for this package
=> Add CBV package

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
closes #127 
Adds github templates:
- pull_request template
- feature_fix template
- bug request template
=> Add GitHub templates

packages/GoogleAnalytics/README.md, packages/GoogleAnalytics/package.json
Bug occurs when you install the package and would like to build
after adding the package. README updated
Updated README example code
Modified **main** key package.json 
Retranspiled
**Checklist**
=> Solve bug module @onaio/google-analytics not found

packages/gatekeeper/dist/components/callback/custom.js, packages/gatekeeper/dist/components/callback/implicit.js, packages/gatekeeper/dist/ducks/gatekeeper.js, packages/gatekeeper/dist/helpers/services.js, packages/gatekeeper/dist/index.js, packages/gatekeeper/dist/types/components/callback/base.d.ts, packages/gatekeeper/dist/types/components/callback/custom.d.ts, packages/gatekeeper/dist/types/components/callback/implicit.d.ts, packages/gatekeeper/dist/types/components/logout.d.ts, packages/gatekeeper/dist/types/index.d.ts, packages/gatekeeper/src/index.ts
Export `useOAuthLogin` which was missing from index.ts
**closes #150**
=> Export useOAuthLogin from package gatekeeper index

packages/DrillDownTable/README.md, packages/DrillDownTable/dist/components/DrillDownTable.js, packages/DrillDownTable/dist/helpers/types.js, packages/DrillDownTable/dist/helpers/utils.js, packages/DrillDownTable/dist/index.js, packages/DrillDownTable/dist/types/components/DrillDownTable.d.ts, packages/DrillDownTable/dist/types/components/HelperComponents/index.d.ts, packages/DrillDownTable/dist/types/components/TableJSX.d.ts, packages/DrillDownTable/dist/types/helpers/types.d.ts, packages/DrillDownTable/dist/types/helpers/utils.d.ts, packages/DrillDownTable/dist/types/index.d.ts, packages/DrillDownTable/src/components/DrillDownTable.tsx, packages/DrillDownTable/src/components/HelperComponents/index.tsx, packages/DrillDownTable/src/components/TableJSX.tsx, packages/DrillDownTable/src/components/tests/__snapshots__/index.test.tsx.snap, packages/DrillDownTable/src/components/tests/index.test.tsx, packages/DrillDownTable/src/helpers/types.ts, packages/DrillDownTable/src/helpers/utils.tsx, packages/DrillDownTable/src/index.tsx
**closes #**
- make function that determines the hierarchy for the drilldown configurable as a prop
**Checklist**
=> Enhance drill down

packages/gatekeeper/dist/helpers/constants.js, packages/gatekeeper/dist/helpers/services.js, packages/gatekeeper/dist/index.js, packages/gatekeeper/dist/types/helpers/constants.d.ts, packages/gatekeeper/dist/types/helpers/services.d.ts, packages/gatekeeper/dist/types/index.d.ts, packages/gatekeeper/src/helpers/constants.ts, packages/gatekeeper/src/helpers/services.ts, packages/gatekeeper/src/helpers/tests/services.test.ts, packages/gatekeeper/src/index.ts
Part of https://github.com/onaio/reveal-frontend/issues/1439
Adds a general function that calls express API to refresh token and push new tokens to the store
**Checklist**
=> Add function to gatekeeper that call for token refresh

packages/DrillDownTable/CHANGELOG.md, packages/DrillDownTable/package.json, packages/Loaders/CHANGELOG.md, packages/Loaders/package.json, packages/connected-private-route/CHANGELOG.md, packages/connected-private-route/package.json, packages/gatekeeper/CHANGELOG.md, packages/gatekeeper/package.json, packages/session-reducer/CHANGELOG.md, packages/session-reducer/package.json
Publish following package with lerna
- @onaio/drill-down-table@1.0.5
- @onaio/loaders@0.0.2
- @onaio/connected-private-route@0.0.12
- @onaio/gatekeeper@0.1.1
- @onaio/session-reducer@0.0.12
=> Publish packages

.eslintrc, packages/GisidaLite/README.md, packages/GisidaLite/dist/types/constants.d.ts, packages/GisidaLite/dist/types/index.d.ts, packages/GisidaLite/package.json, packages/GisidaLite/src/constants.ts, packages/GisidaLite/src/index.tsx, packages/GisidaLite/src/tests/index.test.tsx, packages/GisidaLite/tsconfig.json, setupTests.js, stories/GisidaLite/GisidaLite.stories.tsx, yarn.lock
**closes #157 **
- GisidLite component
- [no-undef eslint  rule override](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors)  
- GisidaLite storybook
- Allow .jsx in .tsx files
- Component Docs
**Checklist**
=> 157 gisida lite mapbox
